### PR TITLE
Delete liveconding.tv and change Twitch category

### PR DESCRIPTION
**Pull request by dreyhiflden**

### CODE REVIEW

**Comment by in-in** [comment]
Do we really need this link to twitch?   
It's hard enough to find something about web development in this mess.

**Comment by dreyhiflden** [comment]
We don't have alternatives, old twitch category is completely empty, now all programing channels on this (Science & Technology) category (but yes, not all streamers correctly set their tags).



And livecoding.tv is gone.

**Comment by in-in** [comment]
I meant to completely remove this section "Live coding streams". This is better than poor quality links. Attempting to find something worthwhile on Twitch is a waste of time. Or I just do not know how to use Twitch :thinking:   

It may be better to add individual links to good channels. I know only one good channel on Twitch: https://www.twitch.tv/noopkat

**Comment by andrew--r** [comment]
@dreyhiflden, thanks, I didn’t notice livecoding.tv became unavailable.

Agree with @in-in, it’s better to have links to individual channels. I’ll replace twitch category link with https://www.twitch.tv/noopkat.

**Pull request merged**
