### PR TITLE
Adding Dutch Fronteers meeting recordings

### PR DESCRIPTION
**Pull request by edwinm**

### CODE REVIEW

**Comment by andrew--r** [comment]
Oh, diff looks too strange. Can you please describe what you added so I add it manually? Or just open new pull request. Thank you :)

**Comment by edwinm** [comment]
If you could add this somewhere:

> ## Dutch language
> 
> - [Fronteers](https://fronteers.nl/videos) — HTML, CSS, JavaScript, Front-end.

Thanks.

**Comment by andrew--r** [comment]
Thank you! Added in 54f860c46fe67099f79d0c84881281fe99040193.

**Comment by edwinm** [comment]
Thanks

**Pull request closed without merging**
